Repository fga-eps-mds/2022-2-CAPJu-Service, pull requests merged in 2023-01, with the labels that each got.

#20 141-Alteração do endpoint de cadastro e edição de fluxos
  src/controllers/FlowController.js
  src/controllers/StageController.js
  src/schemas/Flow.js
  src/validators/Flow.js
Labels: FEATURE

#21 Serviço de envio de e-mail
  package.json
  src/app.js
  src/assets/UnB.png
  src/assets/capju.png
  src/assets/justica_federal.png
  src/controllers/Emailer.js
  src/controllers/FlowController.js
  src/routes.js
  src/tests/__tests__/test_emailer.js
  src/utils/queryMailContents.js
  src/utils/queryUsersNotificate.js
  yarn.lock
Labels: MDS, Tarefa

#23 Não tornar administradores usuários não aceitos
  src/controllers/UnitController.js
  src/tests/__tests__/test_unit_routes.js
Labels: HOTFIX, EASY

#22 Feature/97 cadastro processos com prioridade
  src/controllers/ProcessController.js
  src/routes.js
Labels: MDS, FEATURE
